version: "3.8"

services:
  front:
    container_name: front_react
    image: anime-images-react
    build: ./anime_images_react/api
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    image: anime-images-backend
    build: ./anime_images_backend
    ports:
      - '8000:8000'
    depends_on:
      - front
    environment:
      PYTHONUNBUFFERED: 1

  nginx:
    container_name: nginx
    image: nginx-proxy
    build: ./nginx
    ports:
      - "90:90"
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
